### ISSUE TITLE
Shorten the safepal user identity code

### ISSUE THREAD

**Issue by mbabazigift** [UNFPAInnovation/safepal_web.dashboard#7]
The safepal user identity code should be changed from SPM/W190000712 to SPM19712. SPM being the acronym of safepal, 19 being the year and the other numbers being the user/ reporter identity code.

**Comment by slybard** [comment]
@mbabazigift Actually, the SP is the acronym for SafePal, the "M" denotes that it was submitted via the app ("W" being from the website), "19" is the year. Is there a reason we want to reduce the rest of the code to just 3 extra digits? 3 digits only gives you 1000 different cases. Given the number of reports, a higher number of digits makes it more scalable.

**Comment by innyanzi** [comment]
After reviewing the safepal identity code assignment feature, I recommend may not be changed as it will break the current assignment identity of cases already stored in the database.
